### PR TITLE
Add a meta viewport tag to make the site more mobile-friendly

### PR DESCRIPTION
**Pull request by jessepinho**
## Before
image

## After
image

### CODE REVIEW

**Comment by matkl** [comment]
Thanks. But how do you drag and drop on mobile?

**Comment by jessepinho** [comment]
@matkl I just submitted #3 for that :)

**Comment by jessepinho** [comment]
Love this repo by the way! Thanks for making it :)

**Comment by matkl** [comment]
Wonderful. Thank you!

**Comment by jessepinho** [comment]
@matkl  Thanks for the quick reviews/merges!

**Pull request merged**
